version: 0.0
os: linux
files:
  - source: /themes
    destination: /home/bitnami/wordpress/wp-content/themes
hooks:
  BeforeInstall:
    - location: scripts/date.sh
      timeout: 10
      runas: root