version: 0.0
os: linux
files:
  - source: /themes/industrial-child
    destination: /home/bitnami/wordpress/wp-content/industrial-child
hooks:
  BeforeInstall:
    - location: scripts/date.sh
      timeout: 10
      runas: root